version: '3.8'

services:
  # 1. El motor de la base de datos con el volumen local explicitado
  postgres_db:
    image: postgres:17
    container_name: northwind
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - northwind:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  # 2. El contenedor efímero de Python que puebla la base y muere
  db_initializer:
    image: python:3.12-slim
    container_name: database_init
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_HOST=postgres_db  # CRÍTICO: Dentro de Docker el host es el nombre del servicio
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    command: sh -c "pip install --no-cache-dir -r requirements-init.txt && python database_init.py"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  northwind: # Tu volumen nombrado para persistencia local